default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: mayank1273
  pool: 5

development:
  <<: *default
  database: crud_development

test:
  <<: *default
  database: crud_test

production:
  <<: *default
  database: crud_production
